<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <RootNamespace>MSEMC</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MSEMC.Shared\MSEMC.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MailKit" Version="4.16.0" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="8.4.0" />
    <PackageReference Include="Polly.Extensions" Version="8.6.6" />
    <PackageReference Include="Scriban" Version="7.2.1" />
    <PackageReference Include="Serilog.AspNetCore" Version="8.0.3" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
    <PackageReference Include="Serilog.Sinks.Grafana.Loki" Version="8.3.2" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\Templates\**\*" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" Link="Templates\%(RecursiveDir)%(Filename)%(Extension)" />
  </ItemGroup>

</Project>
